load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "visitable",
    srcs = [
        "property.h",
        "visitable.h",
    ],
    hdrs = [
        "property.h",
        "visitable.h",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
