load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "visitable",
    srcs = [
        "property.hpp",
        "visitable.hpp",
    ],
    hdrs = [
        "property.hpp",
        "visitable.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)

cc_library(
    name = "visitor_base",
    srcs = [
        "visitor_base.hpp",
    ],
    hdrs = [
        "visitor_base.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
