load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "game_session",
    srcs = [
        # "game_session.cpp",
    ],
    hdrs = ["game_session.hpp"],
    visibility = ["//visibility:public"],
    deps = ["@boost.asio"],
)

cc_library(
    name = "player_controller_base",
    srcs = [
        # "player_controller_base.cpp",
    ],
    hdrs = ["player_controller_base.hpp"],
    visibility = ["//visibility:public"],
)
