load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "deck",
    srcs = [
        "Card.h",
        "Deck.cpp",
    ],
    hdrs = ["Deck.h"],
    visibility = ["//visibility:public"],
    deps = [],
)
